In [1]:
import torch 

a = torch.ones(2,2)
a

tensor([[1., 1.],
        [1., 1.]])

In [5]:
a[1,0] = 2
a.shape

torch.Size([2, 2])

In [9]:
points_gpu = torch.tensor([[4., 1.],[5., 3.],[2., 1.]], device = 'mps')


In [15]:
points = 2 * points_gpu
points_cpu = points.to(device='cpu')
points_cpu

tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]])

In [14]:
points

tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]], device='mps:0')