In [22]:
import torch

x = [0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0,6.0, 13.0,21.0]
y = [35.7, 55.9,58.2,81.9,56.3,48.9,33.9,21.8,48.4,60.4,68.4]

print(len(x) == len(y))
x

True


[0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0]

In [23]:
x = torch.tensor(x)
y = torch.tensor(y)

x

tensor([ 0.5000, 14.0000, 15.0000, 28.0000, 11.0000,  8.0000,  3.0000, -4.0000,
         6.0000, 13.0000, 21.0000])

In [24]:
# 선형관계를 가정
def linear_model(x,w,b):
    return w * x + b

def loss_fn(p, x):
    squared_diff = (p-x)**2
    return squared_diff.mean()


In [25]:
# w,b 초기화

w = torch.ones(())
b = torch.zeros(())


In [26]:
p = linear_model(x,w,b)
p

tensor([ 0.5000, 14.0000, 15.0000, 28.0000, 11.0000,  8.0000,  3.0000, -4.0000,
         6.0000, 13.0000, 21.0000])

In [27]:
loss = loss_fn(p,y)
loss

tensor(1763.8848)

In [ ]:
delta = 0.1

# w에 대한 손실함수의 기울기
w_change_rate = (loss_fn(linear_model(x, w+ delta, b), y) / 2.0 * delta) 
b_change_rate = (loss_fn(linear_model(x, w, b+delta), y) / 2.0 * delta) 

lr = 1e-2
w = w - lr * w_change_rate
b = b - lr * b_change_rate




In [28]:
# 미분 계산
# 각 식의 도함수로 표현

def dloss_fn(p, y):
    dsq_diffs = 2 * (p-y) / p.size(0)
    return dsq_diffs

def dw(x,w,b):
    return x

def db(x,w,b):
    return 1.0

#미분 계산한 함수
def grad_fn(x, y, p, w, b):
    dloss_ftp = dloss_fn(p, y)
    dloss_dw = dloss_ftp * dw(x,w,b)
    dloss_db = dloss_ftp * db(x,w,b)
    return torch.stack([dloss_dw.sum(), dloss_db.sum()])

result = grad_fn(x,y,p,w,b)
result

tensor([-989.5273,  -82.6000])

In [32]:
# train loop

def training_loop(epochs, lr,params, x, y):
    for epoch in range(1, epochs +1):
        w, b = params
        p = linear_model(x,w,b)
        loss = loss_fn(p, y)
        grad = grad_fn(x, y, p, w, b)
        params = params - lr * grad

        print('Epoch %d, Loss %f'%(epoch, float(loss)))
        print('params:', params)
        print('grad:', grad)
    
    return params

training_loop(100, 1e-4, torch.tensor([1.0, 0.0]), x, y)

Epoch 1, Loss 1763.884766
params: tensor([1.0990, 0.0083])
grad: tensor([-989.5273,  -82.6000])
Epoch 2, Loss 1667.137939
params: tensor([1.1942, 0.0163])
grad: tensor([-952.2690,  -80.5055])
Epoch 3, Loss 1577.523804
params: tensor([1.2858, 0.0242])
grad: tensor([-916.4115,  -78.4896])
Epoch 4, Loss 1494.515503
params: tensor([1.3740, 0.0318])
grad: tensor([-881.9021,  -76.5494])
Epoch 5, Loss 1417.625977
params: tensor([1.4589, 0.0393])
grad: tensor([-848.6901,  -74.6821])
Epoch 6, Loss 1346.403809
params: tensor([1.5406, 0.0466])
grad: tensor([-816.7266,  -72.8850])
Epoch 7, Loss 1280.430786
params: tensor([1.6191, 0.0537])
grad: tensor([-785.9648,  -71.1552])
Epoch 8, Loss 1219.319824
params: tensor([1.6948, 0.0606])
grad: tensor([-756.3597,  -69.4905])
Epoch 9, Loss 1162.712036
params: tensor([1.7676, 0.0674])
grad: tensor([-727.8675,  -67.8882])
Epoch 10, Loss 1110.275146
params: tensor([1.8376, 0.0741])
grad: tensor([-700.4465,  -66.3461])
Epoch 11, Loss 1061.701660
params: tens

tensor([3.5639, 0.4132])

In [34]:
x2 = 0.1 * x
training_loop(100, 1e-4, torch.tensor([1.0, 0.0]), x2, y)

Epoch 1, Loss 2806.242188
params: tensor([1.0133, 0.0101])
grad: tensor([-132.6823, -101.5000])
Epoch 2, Loss 2803.452148
params: tensor([1.0265, 0.0203])
grad: tensor([-132.6112, -101.4518])
Epoch 3, Loss 2800.665039
params: tensor([1.0398, 0.0304])
grad: tensor([-132.5402, -101.4037])
Epoch 4, Loss 2797.881104
params: tensor([1.0530, 0.0406])
grad: tensor([-132.4693, -101.3556])
Epoch 5, Loss 2795.099365
params: tensor([1.0663, 0.0507])
grad: tensor([-132.3983, -101.3075])
Epoch 6, Loss 2792.320801
params: tensor([1.0795, 0.0608])
grad: tensor([-132.3274, -101.2594])
Epoch 7, Loss 2789.545166
params: tensor([1.0927, 0.0709])
grad: tensor([-132.2566, -101.2114])
Epoch 8, Loss 2786.772461
params: tensor([1.1059, 0.0811])
grad: tensor([-132.1858, -101.1634])
Epoch 9, Loss 2784.002197
params: tensor([1.1192, 0.0912])
grad: tensor([-132.1150, -101.1154])
Epoch 10, Loss 2781.235352
params: tensor([1.1324, 0.1013])
grad: tensor([-132.0443, -101.0674])
Epoch 11, Loss 2778.470947
params: tens

tensor([2.2922, 0.9916])

In [40]:
params1 = torch.tensor([1.0, 0.0], requires_grad= True)

def training_loop2(epochs,params, x, y):
    for epoch in range(1, epochs +1):
        loss = loss_fn(linear_model(x, *params), y)
        loss.backward()

        print('Epoch %d, Loss %f'%(epoch, float(loss)))
        
    
training_loop(100, 1e-4, params1, x, y)



Epoch 1, Loss 1763.884766
params: tensor([1.0990, 0.0083], grad_fn=<SubBackward0>)
grad: tensor([-989.5273,  -82.6000], grad_fn=<StackBackward0>)
Epoch 2, Loss 1667.137939
params: tensor([1.1942, 0.0163], grad_fn=<SubBackward0>)
grad: tensor([-952.2690,  -80.5055], grad_fn=<StackBackward0>)
Epoch 3, Loss 1577.523804
params: tensor([1.2858, 0.0242], grad_fn=<SubBackward0>)
grad: tensor([-916.4115,  -78.4896], grad_fn=<StackBackward0>)
Epoch 4, Loss 1494.515503
params: tensor([1.3740, 0.0318], grad_fn=<SubBackward0>)
grad: tensor([-881.9021,  -76.5494], grad_fn=<StackBackward0>)
Epoch 5, Loss 1417.625977
params: tensor([1.4589, 0.0393], grad_fn=<SubBackward0>)
grad: tensor([-848.6901,  -74.6821], grad_fn=<StackBackward0>)
Epoch 6, Loss 1346.403809
params: tensor([1.5406, 0.0466], grad_fn=<SubBackward0>)
grad: tensor([-816.7266,  -72.8850], grad_fn=<StackBackward0>)
Epoch 7, Loss 1280.430786
params: tensor([1.6191, 0.0537], grad_fn=<SubBackward0>)
grad: tensor([-785.9648,  -71.1552], grad

tensor([3.5639, 0.4132], grad_fn=<SubBackward0>)

In [41]:
print(params1.grad)

None


In [46]:
# 자동미분 + 옵티마이저 활용
import torch.optim as optim
def torch_training_loop(epochs, optimizer, params, x, y):
    for epoch in range(1, epochs + 1):
        p = linear_model(x, *params)
        loss = loss_fn(p, y)

        if params.grad is not None:
            params.grad.zero_()

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    return params

params = torch.tensor([1.0, 0.0], requires_grad= True)
lr = 1e-4
optimizer = optim.SGD([params], lr = lr)
torch_training_loop(200, optimizer, params, x, y)

tensor([3.6048, 0.6825], requires_grad=True)